### ISSUE TITLE
Issue with latest versions of next-auth and nextjs

### ISSUE THREAD

**Issue by jhylton** [Jenyus-Org/next-auth-saml#3]
HI there,

I was able to get your solution  working with my external IDP (thanks for the example!) however when I looked to bring this into my current app i realized the project kinda broke on the latest version of next-auth. I wonder if you could have a quick look to see if I am missing something. Basically the callback for session never gets called and thus I can not gain access to user information in the session.

here is what the current [...nextauth].js. Your example seems the be the best option moving forward with next-auth. 

```javascript
export default NextAuth({
  providers: [
    CredentialsProvider({
      id: "saml",
      name: "saml",
      authorize: async ({ samlBody }) => {
        samlBody = JSON.parse(decodeURIComponent(samlBody));

        const postAssert = (identityProvider, samlBody) =>
          new Promise((resolve, reject) => {
            serviceProvider.post_assert(
              identityProvider,
              {
                request_body: samlBody,
              },
              (error, response) => {
                if (error) {
                  reject(error);
                }
                resolve(response);
              }
            );
          });

        try {
          const { user } = await postAssert(identityProvider, samlBody);
          return user;
        } catch (error) {
          console.error(error);
          return null;
        }
      },
    }),
  ],
  pages: {
    signIn: "/login",
  },
  callbacks: {
    jwt: (token, user) => {
      console.log('in  jwt')
      if (user) {
        return {
          user,
        };
      }

      return token;
    },
    session: (session, { user }) => {
      console.log('in session')
      return {
        ...session,
        user,
      };
    },
  },
```

**Comment by jhylton** [comment]
nevermind, i figured it out :) with the version 4 you need to set the session strategy = 'jwt'. I needed to manipulate the user information in 'signIn' callback to get the structure I needed. 

Many thanks for your example as I finally have saml working in nextAuth.

**Comment by LarsBuur** [comment]
@jhylton  - can you provide more details about how you made it work with next-auth v. 4?
